export { default as AppMain } from './AppMain.vue'
export { default as NavBar } from './navbar/index.vue'
export { default as Settings } from './settings/index.vue'
export { default as SideBar } from './sidebar/index.vue'
export { default as TagsView } from './tagsView/index.vue'
