export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './Navbar.vue'
// export { default as Settings } from './setting/index.vue'
export { default as Sidebar } from './sidebar/index.vue'
export { default as TagsView } from './tagsView/index.vue'
